services:

  redis:
    image: redis:alpine
    container_name: redis_app
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  webapp:
    image: node_app:test
    build: .
    container_name: node_app
    ports:
      - "8080:8080"
    environment:
      APP_PORT: "8080" 
      REDIS_ADDRESS: "redis"
      REDIS_PORT: "6379" 
    depends_on:
      redis:
        condition: service_healthy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - '-port=8081'
    ports:
      - "8081:8081"
    volumes: 
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    devices: 
      - "/dev/kmsg"
    privileged: true
    depends_on:
    - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - cadvisor

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    ports:
      - 9121:9121
    command:
      - '--redis.addr=redis://redis:6379'
    depends_on:
    - redis