global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cAdvisor"
    static_configs:
      - targets: ["cadvisor:8081"]
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

