FROM node:16.0.0-alpine3.11

USER node

WORKDIR /usr/src/app/app-ui

COPY --chown=node:node package*.json ./

RUN npm install @angular/cli @angular-devkit/build-angular && npm ci && npm cache clean --force

EXPOSE 4201

CMD ["npm", "start"]
